/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation("net.dv8tion:JDA:5.0.0-alpha.11")
    implementation("org.mongodb:mongodb-driver-async:3.12.11")
    implementation("com.squareup.okhttp3:okhttp:4.9.3")
    implementation("org.json:json:20220320")
}

group = "tv.banko"
version = "1.0-SNAPSHOT"
description = "ValorantEvent"
java.sourceCompatibility = JavaVersion.VERSION_17

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}
